server:
  port: 8080

application:
  security:
    jwt:
      secret-key: Mcvb1KwPaVjhnkBfwUfdHDX2vfWleAZgaJ8XJr6cBsvNPkP19UvVAiMw76zFHW6ZhHsI
      expiration: 86400000 
      refresh-token:
        expiration: 604800000 

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/spring_login
    username: root
    password: 

  sql:
    init:
      mode: always 

  main:
    web-application-type: reactive
